# Generated by Django 5.0.4 on 2024-05-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
